### ISSUE TITLE
INSTALL does not work 

### ISSUE THREAD

**Issue by wernerflamme** [lausser/check_sap_health#15]
Hi,

in the file INSTALL I read `Briefly, the shell commands './configure; make; make install' should configure, build, and install this package.`. I think so, yes. But after a `git clone` I do not have a file named `configure`, so I can't run it. How do I get it?  "automake" and "autoconf" just give errors.

**Comment by lausser** [comment]
Thats related to the tar.gz package. If you clone the git repository, you have to run autoreconf in order to create the configure file.

**Comment by wernerflamme** [comment]
Thanks for mentioning this so clearly in the documentation.

**Comment by wernerflamme** [comment]
```
 # autoreconf
Makefile.am:4: warning: shell which dos2unix || which fromdos: non-POSIX variable name
Makefile.am:4: (probably a GNU make extension)
```
using backticks instead of $( ...) gets rid of the warning
