### ISSUE TITLE
Wrong result using failed-jobs option

### ISSUE THREAD

**Issue by soundpassion** [lausser/check_sap_health#17]
Dear guys,

after we patched Netweaver 7.50 to SP23 the check for failed jobs give us the following message even if there are failed jobs in the system:

"OK - all jobs finished in time with status ok"

all other options works correctly, we already checked that the temporary file ( --statefilesdir) is generated correctly.

Please help to fix this issue.

thanks in advance

A.

**Comment by soundpassion** [comment]
#update @lausser 
if I use the option list-jobs i see that there are some problems to convert the data extracted from TBTCO
![image](https://user-images.githubusercontent.com/93484028/180153621-9e1b11af-b1f9-4acf-9c53-fc355b92bd78.png)

This is related to the problem for sure

**Comment by soundpassion** [comment]
I found the problem, starting from SAP NW SP22 SAP the function module RFC_READ_TABLE extract the fields in a different order.
Line 4114 must be changed:
FROM
my @fields = qw(JOBNAME SDLUNAME STRTDATE STRTTIME ENDDATE ENDTIME STATUS SDLSTRTDT SDLSTRTTM);

TO
**_< EDIT - My solution was not 100% correct, see below for the right one >_**

et voila'

byeeeeee

**Comment by lausser** [comment]
Actually the function call should return the fields in the order you told it:
```
    my @fields = qw(JOBNAME SDLUNAME STRTDATE STRTTIME ENDDATE ENDTIME STATUS SDLSTRTDT SDLSTRTTM);
    $fc->FIELDS([map { { 'FIELDNAME' => $_ } } @fields]);
    $fc->invoke;
```
This should mean that after the invoke the records in $fc->DATA contain the values in exact this order. A customer told me that
my @fields = qw(JOBNAME SDLSTRTDT SDLSTRTTM SDLUNAME STRTDATE STRTTIME ENDDATE ENDTIME STATUS);
works for him. We tried
```
...
    my @fields = qw(JOBNAME SDLUNAME STRTDATE STRTTIME ENDDATE ENDTIME STATUS SDLSTRTDT SDLSTRTTM);
    $fc->FIELDS([map { { 'FIELDNAME' => $_ } } @fields]);
    $fc->invoke;
    my @return_fields = $fc->FIELDS;
    printf "ORIGINALFIELDS %s\n", Data::Dumper::Dumper(\@fields);
    printf "RETURNFIELDS %s\n", Data::Dumper::Dumper(\@return_fields);
    die "thats enough";
    @{$self->{jobs}} = sort {
...
```
and he told me that in older systems (which had no problem at all), the order of RETURNFIELDS were identical to the ORIGINALFIELDS, no matter how the ORIGINALFIELDS were arranged. But with systems that showed the error, the returned fields had a fixed order under all circumstances.
Now there is a difference. 
He says: JOBNAME SDLSTRTDT SDLSTRTTM SDLUNAME STRTDATE STRTTIME ENDDATE ENDTIME STATUS
You say: JOBNAME STRTDATE STRTTIME SDLUNAME ENDDATE ENDTIME SDLSTRTDT SDLSTRTTM STATUS
Can you please hve a look at SDLSTRTTM  and STRTTIME? The SDLSTRTTM can never be smaller than STRTTIME.

**Comment by soundpassion** [comment]
yeah, you're absolutely right.
Sorry for my lack of accuracy, I was so excited to have finally found the fix (I'm not a programmer).
With my order, the delay column is negative and the runtime has a wrong value instead of 0 (the actual runtime), even start time is wrong:
![image](https://user-images.githubusercontent.com/93484028/180346944-b5786a2d-85fb-4f74-b5c3-226da799fa1f.png)

You're customer is right than, and after I use his order the result become correct:
![image](https://user-images.githubusercontent.com/93484028/180347525-d9f3bc1e-4175-4f29-b053-13370c22ea4f.png)

Regarding the retro compatibility with the older systems (even very old), I confirm that both fields orders works correctly (the original and you're customer's one).

Thank you for sharing.

**Comment by lausser** [comment]
Here we go....
[https://labs.consol.de/nagios/check_sap_health/index.html#download](url)
