### ISSUE TITLE
Wrong ENDATE/ENDTIME calculation in plugins-scripts/Classes/SAP/Netweaver/Component/BackgroundjobSubsystem.pm line 20

### ISSUE THREAD

**Issue by Ysincit** [lausser/check_sap_health#19]
Hi,
line 20 in plugins-scripts/Classes/SAP/Netweaver/Component/BackgroundjobSubsystem.pm:
my $condition = sprintf "ENDDATE >= '%s' AND ENDTIME > '%s'", $fromdate, $fromtime;
needs to be changed into:
my $condition = sprintf "ENDDATE > '%s' OR ( ENDDATE = '%s' AND ENDTIME > '%s' )", $fromdate, $fromdate, $fromtime;
or the time slots from 00:00 to ENDTIME for dates > ENDDATE are excluded.
Best regards!

**Comment by lausser** [comment]
Thanks, it's in version 3.1.0.1 (which will be in OMD >= 20230307)
