### ISSUE TITLE
no mtes Output.

### ISSUE THREAD

**Issue by sdouce** [lausser/check_sap_health#6]
We would like to know if it is possible for a SAP Check using the check_sap_health plugin that queries the CCMS to consider the "no mtes" output as an OK state and not as an unknown state.
Indeed, the nodes in the CCMS tend to disappear punctually and from time to time the check returns a bad return while the node exists. This is why we would like this condition to generate no anomaly.

**Comment by lausser** [comment]
Ok, i just added something. 
If you run check_sap_health ...... --mitigation ok, then "no mtes" will be an OK state. (You could also say --mitigation warning fror example)
Will be published the next days.

**Comment by sdouce** [comment]
Thank You ...
